# Generated by Django 2.2.4 on 2019-08-01 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compressor_data', '0003_auto_20190801_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='company_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='publish_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 13, 57, 46, 478647, tzinfo=utc)),
        ),
    ]
