# Generated by Django 2.2.4 on 2019-08-02 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compressor_data', '0005_auto_20190801_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressor_serial_number', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('year_of_purchase', models.CharField(max_length=12)),
                ('anydesk_num', models.CharField(max_length=30)),
                ('total_running_hrs', models.CharField(max_length=7)),
                ('change_fule_in', models.CharField(max_length=7)),
                ('maintance_in', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('user1_mobile', models.CharField(max_length=10)),
                ('user2_mobile', models.CharField(max_length=10)),
                ('user3_mobile', models.CharField(max_length=10)),
                ('dealer_name', models.CharField(max_length=30)),
                ('dealer1_mobile', models.CharField(max_length=10)),
                ('dealer2_mobile', models.CharField(max_length=10)),
                ('craeted_date_and_time', models.DateTimeField(default=datetime.datetime(2019, 8, 2, 7, 54, 30, 466680, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='User_Details',
        ),
        migrations.AddField(
            model_name='compressor_data',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compressor_data.User_Detail'),
        ),
    ]
